### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by binarica** [app-outlet/app-outlet.github.io#5]
It looks like multiple images are missing from the `app-outlet` repository tree.

Example: https://github.com/app-outlet/app-outlet/raw/master/src/assets/banner.png

![image](https://user-images.githubusercontent.com/9634969/116477432-fcfa9f80-a852-11eb-964a-e9ab7afda6a6.png)

**Comment by MessiasLima** [comment]
Thank you. I will update this page as soon as possible
